# ==================================================
# FILE: roles/postgress/handlers/main.yml (database)
# ==================================================
---
- name: postgresql-client
  systemd:
    name: psql
    state: restarted

- name: Reload postgress
  systemd:
    name: psql
    state: reloaded

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted

- name: Reload PostgreSQL
  systemd:
    name: postgresql
    state: reloaded