# ==================================================
# FILE: common handlers
# ==================================================
---
- name: Restart qemu
  systemd:
    name: qemu-guest-agent
    state: restarted

# - name: Reload PHP-FPM
#   systemd:
#     name: php8.3-fpm
#     state: reloaded
