# ==================================================
# FILE: roles/common/tasks/main.yml
# Common tasks to set up server
# define /var/www/html directory
# update and install 
# ==================================================

---    

### update teh apt cache and list, set set time to 1 hour/Studen
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

### Full update for all packages
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    
# Most servers have nginx so creat /www dir
# Ensure /var/www/html exists (matches Dockerfile WORKDIR)
- name: Ensure /var/www/html directory exists
  become: yes
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

# install the basic packages common by php nginx apache2 rust and others.
- name: "STEP 1: Install core system dependencies"
  apt:
    name:
      - nginx
      - git
      - unzip
      - curl
      - openssl 
      - libzip-dev
      - zlib1g-dev
      - libxml2-dev
      - libcurl4-openssl-dev
      - libgmp-dev
      - libffi-dev
      - pkg-config
      - libpq-dev
      - ffmpeg
      - tree
    state: present