### Database Valut Vars
##
---
testing root: xnZ1coMKqe8ROwq9xLAIZaJHx8n5W1
testing peer_beta: A4D0191727C8E53F3D20E0005CCBAF1128534F35115C65FB52AE33F0306B482D
staging root: T8zkuEl4vZPGmS27EKnWfJ99pt9qhxEH
staging peer_beta: CF4D0E40491C5649B2039F03C11C07B0A24D1BE2D8B40BE7CFCA4919E36674FC
prod root: IdLWkRnECahLbTUs4sL!RZSxzNcXEt
prod peer_beta: A1AE123F905ABF1D38950A1008E2867F0F82FF50F8FD3424016CB2F17D483C84
prod_peer_extra: C1E9CDD8456A739A6BA9BB33A860106FFBA7A75F72319EB7E45B93FE819657B4