$ANSIBLE_VAULT;1.1;AES256
66313030336566643764363732396331386636383738666339366135666231663864653231323630
6330396565643234363037656336346536376234323563300a653638656462383965633233643266
31316534363532623135633038643063393939356333363233383765363036343663323062663730
6431643761356164320a623839353864306230353461653732643239366162393032653435356231
65363036353932616330303337663965346538323137393161653162613861613064643836326234
64633664633765656233633734666137373331346331366239353666616466633831643131393439
32633830633730636331646663393032616164396637623363643530643535363261303930306336
33343830363434313035653961333964643363393739383238633533303964636632363534363537
34373434663266373539313766636432356336653233363565633462326561653631313165346132
30666438623931333461326134316636363765323931356161343239663561656138373364663835
33306639656134393161633430636232383339623536633862366439646366393937393561653064
62666161366266353637303334303338373339393266646139313631356161626635396232616464
61633239656131386636363137396131626563306538663732623537363865393362393764393965
31306264656532643164353136633631363338333561393565626537313566653037393037313763
34333963643533646665633038303766363064393232316630343633323033353966303536666331
34633961316236393861393338356331346662336138343133663634376562373363323239663437
37666163623064323463386664646632366264333136626664313861303131326335313931393432
61373735653034333937656434396166653330636237396366613530643032316162353166666338
31393865653334393732343732303037353931303134663436396566383831656666643761663733
63303430646636613763663736366639346263636366363235363135633832623630326664333761
38613831666437663831656235303331366263336634656662623834626163653230623834323061
37373034396561643461376430303430653338636230373666343461353165386432386537636537
30623832393333313762656237343866623335333866343961353333393664623336333639383031
30353630643433646564386230306636393061343766303732663765383036363666623133333233
61386334303063656238343665383434313131333530346233316266636562663333383934636236
37396566376438653533313135356163333665396334386264613831366664386365613535653265
61373832646230366161643561363763623036316236386636386363326564303030353466663962
36613831303932326538313637306662363034646236333934643539323133336165316565366536
3862
